### ISSUE TITLE
Wont working on telegram

### ISSUE THREAD

**Issue by rsoorajs** [Sea-n/tgpe#2]
Tested on web,its working..but not working on telegram .can you help me ?

i just edited config.php as like this.but not working..

> <?php

define('TG_ADMINS', [
	638xxxxxxxxxxxx  # Sean
]);
define('HTTP_API_TOKENS', [
	'guest' => 'guest',
	'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx(put tg token here)' => 'admin'

> ]);

**Comment by Sea-n** [comment]
The Telegram Bot part is my not-so opened framework, you have to modify for your environment.

Just replace the `$TG` part to your variable, let me know if you don't know particular function does.

Code for reference: https://www.sean.taipei/telegram/
